import type { AppState, Customer, Order, QCChecklist } from "./types";

const qcPass: QCChecklist = {
  correctFile: true,
  correctQuantity: true,
  correctPaper: true,
  correctColor: true,
  correctSize: true,
  correctFinishing: true,
  noDefects: true,
  properPackaging: true,
  passedAt: "2026-09-03T10:20:00.000Z",
  inspector: "Ana Reyes",
};

const customers: Customer[] = [
  {
    id: "cus-abc",
    name: "Liza Mercado",
    mobile: "09171234567",
    email: "purchasing@abc-mfg.ph",
    company: "ABC Manufacturing",
    type: "company",
    billing: "monthly",
    address: "Laguna Technopark, Biñan",
    authorizedUsers: ["Purchasing", "HR", "Safety", "Admin", "Marketing"],
    vip: true,
  },
  {
    id: "cus-juan",
    name: "Juan Dela Cruz",
    mobile: "09181220011",
    email: "juan.delacruz@gmail.com",
    type: "individual",
    billing: "per_order",
    address: "Poblacion, Cabuyao",
    vip: false,
  },
  {
    id: "cus-xyz",
    name: "Carlo Tan",
    mobile: "09175550990",
    email: "carlo@xyztrading.ph",
    company: "XYZ Trading",
    type: "company",
    billing: "per_order",
    address: "Santa Rosa Commercial Complex",
    vip: false,
  },
  {
    id: "cus-maria",
    name: "Maria Santos",
    mobile: "09228881122",
    email: "maria.santos@outlook.com",
    type: "individual",
    billing: "per_order",
    address: "Brgy. Banay-Banay, Cabuyao",
    vip: false,
  },
  {
    id: "cus-def",
    name: "Patricia Ong",
    mobile: "09190003344",
    email: "admin@defcorp.ph",
    company: "DEF Corporation",
    type: "vip",
    billing: "monthly",
    address: "Calamba Premiere International Park",
    authorizedUsers: ["Admin", "Marketing"],
    vip: true,
  },
];

function ev(id: string, at: string, title: string, detail?: string) {
  return { id, at, title, detail };
}

const orders: Order[] = [
  {
    id: "ord-001",
    ticket: "PTG-20260903-001",
    createdAt: "2026-09-03T08:12:00.000Z",
    customerId: "cus-abc",
    files: [
      {
        id: "f-1",
        name: "Safety Poster.pdf",
        type: "application/pdf",
        size: 2400000,
        dataUrl:
          "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='800' height='1100'><rect width='100%25' height='100%25' fill='%230f172a'/><text x='50%25' y='46%25' text-anchor='middle' fill='white' font-size='48' font-family='Arial'>SAFETY FIRST</text><text x='50%25' y='54%25' text-anchor='middle' fill='%2394a3b8' font-size='22'>Print-to-Go demo poster</text></svg>",
        spec: {
          service: "Posters",
          paperSize: "A3",
          paperType: "Glossy",
          color: "Colored",
          sides: "Single-sided",
          quantity: 20,
          finishing: ["Lamination"],
        },
      },
      {
        id: "f-2",
        name: "Employee Handbook.pdf",
        type: "application/pdf",
        size: 8200000,
        spec: {
          service: "Document Printing",
          paperSize: "A4",
          paperType: "Bond Paper",
          color: "Colored",
          sides: "Double-sided",
          quantity: 40,
          finishing: ["Binding"],
        },
      },
    ],
    fulfillment: "delivery",
    delivery: {
      contactName: "Main Security",
      mobile: "09171234567",
      pin: {
        lat: 14.273,
        lng: 121.075,
        address: "Laguna Technopark, Biñan, Laguna",
        landmark: "Near warehouse gate",
        building: "Plant 2",
        gate: "Main security gate",
        instructions: "Please call when you arrive.",
      },
    },
    specialInstructions: "Deliver to main security gate.",
    status: "printing",
    paymentStatus: "monthly",
    priority: "high",
    quotation: {
      lines: [
        { id: "q1", description: "Safety Poster · 20 A3 Colored + lamination", amount: 1500 },
        { id: "q2", description: "Employee Handbook · 40 A4 Colored + binding", amount: 850 },
        { id: "q3", description: "Delivery · Zone 2", amount: 150 },
      ],
      discount: 0,
      sentAt: "2026-09-03T08:40:00.000Z",
    },
    amountPaid: 0,
    timeline: [
      ev("t1", "2026-09-03T08:12:00.000Z", "Request submitted"),
      ev("t2", "2026-09-03T08:40:00.000Z", "Quotation sent", "₱2,500"),
      ev("t3", "2026-09-03T08:55:00.000Z", "Customer accepted quotation"),
      ev("t4", "2026-09-03T09:05:00.000Z", "Charged to monthly account"),
      ev("t5", "2026-09-03T09:30:00.000Z", "Printing started"),
    ],
  },
  {
    id: "ord-002",
    ticket: "PTG-20260903-002",
    createdAt: "2026-09-03T09:04:00.000Z",
    customerId: "cus-juan",
    files: [
      {
        id: "f-3",
        name: "Family Photos.zip",
        type: "application/zip",
        size: 18000000,
        spec: {
          service: "Photo Printing",
          paperSize: "Custom",
          customSize: "4R",
          paperType: "Photo Paper",
          color: "Colored",
          sides: "Single-sided",
          quantity: 20,
          finishing: ["Packaging"],
        },
      },
    ],
    fulfillment: "pickup",
    pickupNote: "Will pick up after 5 PM",
    status: "ready",
    paymentStatus: "paid",
    priority: "normal",
    quotation: {
      lines: [
        { id: "q4", description: "20 × 4R photo prints", amount: 300 },
        { id: "q5", description: "Photo sleeve packaging", amount: 50 },
      ],
      discount: 0,
      sentAt: "2026-09-03T09:20:00.000Z",
    },
    amountPaid: 350,
    qc: qcPass,
    timeline: [
      ev("t6", "2026-09-03T09:04:00.000Z", "Request submitted"),
      ev("t7", "2026-09-03T09:20:00.000Z", "Quotation sent", "₱350"),
      ev("t8", "2026-09-03T09:28:00.000Z", "Paid via GCash"),
      ev("t9", "2026-09-03T10:15:00.000Z", "Printing complete"),
      ev("t10", "2026-09-03T10:22:00.000Z", "QC passed · ready for pickup"),
    ],
  },
  {
    id: "ord-003",
    ticket: "PTG-20260903-003",
    createdAt: "2026-09-03T10:18:00.000Z",
    customerId: "cus-xyz",
    files: [
      {
        id: "f-4",
        name: "Promo Flyers.pdf",
        type: "application/pdf",
        size: 3600000,
        spec: {
          service: "Flyers",
          paperSize: "A4",
          paperType: "Matte",
          color: "Colored",
          sides: "Double-sided",
          quantity: 500,
          finishing: ["Cutting", "Folding"],
        },
      },
    ],
    fulfillment: "delivery",
    delivery: {
      contactName: "Carlo Tan",
      mobile: "09175550990",
      pin: {
        lat: 14.3123,
        lng: 121.1114,
        address: "Santa Rosa Commercial Complex, Santa Rosa, Laguna",
        landmark: "Beside the loading bay",
        floor: "Ground",
        instructions: "Ask for Carlo at the store counter.",
      },
    },
    status: "quotation",
    paymentStatus: "pending",
    priority: "normal",
    quotation: {
      lines: [
        { id: "q6", description: "500 A4 colored flyers, double-sided", amount: 4000 },
        { id: "q7", description: "Cutting and folding", amount: 350 },
        { id: "q8", description: "Delivery · Zone 2", amount: 150 },
      ],
      discount: 0,
      sentAt: "2026-09-03T10:45:00.000Z",
    },
    amountPaid: 0,
    timeline: [
      ev("t11", "2026-09-03T10:18:00.000Z", "Request submitted"),
      ev("t12", "2026-09-03T10:45:00.000Z", "Quotation sent", "₱4,500"),
    ],
  },
  {
    id: "ord-004",
    ticket: "PTG-20260902-004",
    createdAt: "2026-09-02T14:10:00.000Z",
    customerId: "cus-maria",
    files: [
      {
        id: "f-5",
        name: "Barangay Documents.pdf",
        type: "application/pdf",
        size: 900000,
        spec: {
          service: "Document Printing",
          paperSize: "A4",
          paperType: "Bond Paper",
          color: "Black & White",
          sides: "Single-sided",
          quantity: 70,
          finishing: ["Stapling"],
        },
      },
    ],
    fulfillment: "delivery",
    delivery: {
      contactName: "Maria Santos",
      mobile: "09228881122",
      pin: {
        lat: 14.2812,
        lng: 121.1268,
        address: "Brgy. Banay-Banay, Cabuyao, Laguna",
        landmark: "Blue gate near sari-sari store",
        instructions: "Leave with guard if Maria is out.",
      },
    },
    status: "delivered",
    paymentStatus: "cod",
    priority: "normal",
    quotation: {
      lines: [
        { id: "q9", description: "70 A4 B&W documents", amount: 280 },
        { id: "q10", description: "Stapling", amount: 20 },
        { id: "q11", description: "Delivery · Zone 1", amount: 50 },
      ],
      discount: 0,
      sentAt: "2026-09-02T14:25:00.000Z",
    },
    amountPaid: 350,
    qc: qcPass,
    pod: {
      recipientName: "Juan Santos",
      deliveredAt: "2026-09-02T16:43:00.000Z",
      confirmation: true,
      signatureName: "J. Santos",
      remarks: "Received at the gate",
    },
    runId: "run-001",
    driver: "John Ramos",
    timeline: [
      ev("t13", "2026-09-02T14:10:00.000Z", "Request submitted"),
      ev("t14", "2026-09-02T15:00:00.000Z", "Printed and QC passed"),
      ev("t15", "2026-09-02T16:10:00.000Z", "Out for delivery"),
      ev("t16", "2026-09-02T16:43:00.000Z", "Delivered", "Received by Juan Santos"),
    ],
  },
  {
    id: "ord-005",
    ticket: "PTG-20260903-005",
    createdAt: "2026-09-03T11:02:00.000Z",
    customerId: "cus-def",
    files: [
      {
        id: "f-6",
        name: "Business Cards.pdf",
        type: "application/pdf",
        size: 1200000,
        spec: {
          service: "ID / Cards",
          paperSize: "Custom",
          customSize: "3.5 × 2 in",
          paperType: "Cardstock",
          color: "Colored",
          sides: "Double-sided",
          quantity: 200,
          finishing: ["Cutting", "Lamination"],
        },
      },
    ],
    fulfillment: "delivery",
    delivery: {
      contactName: "Patricia Ong",
      mobile: "09190003344",
      pin: {
        lat: 14.2117,
        lng: 121.1653,
        address: "Calamba Premiere International Park, Calamba, Laguna",
        building: "DEF Tower",
        floor: "5",
        office: "Marketing",
        instructions: "Before 3:00 PM please.",
      },
    },
    specialInstructions: "Customer requested delivery before 3:00 PM.",
    status: "ready",
    paymentStatus: "paid",
    priority: "urgent",
    quotation: {
      lines: [
        { id: "q12", description: "200 business cards, laminated", amount: 2200 },
        { id: "q13", description: "Rush fee", amount: 150 },
        { id: "q14", description: "Delivery · Zone 3", amount: 120 },
      ],
      discount: 0,
      sentAt: "2026-09-03T11:20:00.000Z",
    },
    amountPaid: 2470,
    qc: qcPass,
    timeline: [
      ev("t17", "2026-09-03T11:02:00.000Z", "Request submitted"),
      ev("t18", "2026-09-03T11:20:00.000Z", "Quotation accepted"),
      ev("t19", "2026-09-03T13:40:00.000Z", "QC passed · ready for delivery"),
    ],
  },
  {
    id: "ord-006",
    ticket: "PTG-20260903-006",
    createdAt: "2026-09-03T07:40:00.000Z",
    customerId: "cus-abc",
    files: [
      {
        id: "f-7",
        name: "Company Logo.jpg",
        type: "image/jpeg",
        size: 640000,
        spec: {
          service: "Stickers",
          paperSize: "Custom",
          customSize: "3 inch round",
          paperType: "Sticker Paper",
          color: "Colored",
          sides: "Single-sided",
          quantity: 100,
          finishing: ["Cutting"],
        },
      },
    ],
    fulfillment: "delivery",
    delivery: {
      contactName: "HR Desk",
      mobile: "09171234567",
      pin: {
        lat: 14.2742,
        lng: 121.0771,
        address: "Laguna Technopark, Biñan, Laguna",
        building: "Admin building",
        floor: "2",
        office: "HR",
      },
    },
    status: "new",
    paymentStatus: "pending",
    priority: "normal",
    amountPaid: 0,
    timeline: [ev("t20", "2026-09-03T07:40:00.000Z", "Request submitted")],
  },
  {
    id: "ord-007",
    ticket: "PTG-20260901-007",
    createdAt: "2026-09-01T09:00:00.000Z",
    customerId: "cus-def",
    files: [
      {
        id: "f-8",
        name: "September Brochures.pdf",
        type: "application/pdf",
        size: 5400000,
        spec: {
          service: "Flyers",
          paperSize: "A4",
          paperType: "Glossy",
          color: "Colored",
          sides: "Double-sided",
          quantity: 300,
          finishing: ["Folding"],
        },
      },
    ],
    fulfillment: "delivery",
    delivery: {
      contactName: "Patricia Ong",
      mobile: "09190003344",
      pin: {
        lat: 14.2117,
        lng: 121.1653,
        address: "Calamba Premiere International Park, Calamba, Laguna",
      },
    },
    status: "completed",
    paymentStatus: "monthly",
    priority: "normal",
    quotation: {
      lines: [
        { id: "q15", description: "300 A4 glossy brochures", amount: 3600 },
        { id: "q16", description: "Delivery · Zone 3", amount: 120 },
      ],
      discount: 0,
    },
    amountPaid: 0,
    pod: {
      recipientName: "Patricia Ong",
      deliveredAt: "2026-09-01T16:10:00.000Z",
      confirmation: true,
    },
    timeline: [
      ev("t21", "2026-09-01T09:00:00.000Z", "Request submitted"),
      ev("t22", "2026-09-01T16:10:00.000Z", "Delivered and completed"),
    ],
  },
  {
    id: "ord-008",
    ticket: "PTG-20260903-008",
    createdAt: "2026-09-03T12:05:00.000Z",
    customerId: "cus-xyz",
    files: [
      {
        id: "f-9",
        name: "Price List.pdf",
        type: "application/pdf",
        size: 400000,
        spec: {
          service: "Forms",
          paperSize: "Legal",
          paperType: "Bond Paper",
          color: "Black & White",
          sides: "Single-sided",
          quantity: 80,
          finishing: ["Stapling"],
        },
      },
    ],
    fulfillment: "delivery",
    delivery: {
      contactName: "Carlo Tan",
      mobile: "09175550990",
      pin: {
        lat: 14.314,
        lng: 121.109,
        address: "Santa Rosa Commercial Complex, Santa Rosa, Laguna",
      },
    },
    status: "quality_check",
    paymentStatus: "paid",
    priority: "low",
    quotation: {
      lines: [
        { id: "q17", description: "80 Legal B&W forms", amount: 400 },
        { id: "q18", description: "Delivery · Zone 2", amount: 80 },
      ],
      discount: 0,
    },
    amountPaid: 480,
    timeline: [
      ev("t23", "2026-09-03T12:05:00.000Z", "Request submitted"),
      ev("t24", "2026-09-03T13:30:00.000Z", "Moved to quality check"),
    ],
  },
  {
    id: "ord-009",
    ticket: "PTG-20260903-009",
    createdAt: "2026-09-03T06:50:00.000Z",
    customerId: "cus-juan",
    files: [
      {
        id: "f-10",
        name: "Resume.pdf",
        type: "application/pdf",
        size: 220000,
        spec: {
          service: "Document Printing",
          paperSize: "A4",
          paperType: "Matte",
          color: "Colored",
          sides: "Single-sided",
          quantity: 10,
          finishing: [],
        },
      },
    ],
    fulfillment: "pickup",
    status: "awaiting_confirmation",
    paymentStatus: "pending",
    priority: "normal",
    quotation: {
      lines: [{ id: "q19", description: "10 A4 colored resumes", amount: 150 }],
      discount: 0,
      sentAt: "2026-09-03T07:10:00.000Z",
    },
    amountPaid: 0,
    timeline: [
      ev("t25", "2026-09-03T06:50:00.000Z", "Request submitted"),
      ev("t26", "2026-09-03T07:10:00.000Z", "Quotation sent", "₱150"),
    ],
  },
  {
    id: "ord-010",
    ticket: "PTG-20260828-018",
    createdAt: "2026-08-28T11:00:00.000Z",
    customerId: "cus-abc",
    files: [
      {
        id: "f-11",
        name: "Company Handbook.pdf",
        type: "application/pdf",
        size: 7600000,
        spec: {
          service: "Booklets",
          paperSize: "A4",
          paperType: "Bond Paper",
          color: "Colored",
          sides: "Double-sided",
          quantity: 25,
          finishing: ["Spiral Binding"],
        },
      },
    ],
    fulfillment: "delivery",
    delivery: {
      contactName: "Liza Mercado",
      mobile: "09171234567",
      pin: {
        lat: 14.273,
        lng: 121.075,
        address: "Laguna Technopark, Biñan, Laguna",
      },
    },
    status: "completed",
    paymentStatus: "monthly",
    priority: "normal",
    quotation: {
      lines: [{ id: "q20", description: "25 handbooks, spiral bound", amount: 1200 }],
      discount: 0,
    },
    amountPaid: 0,
    timeline: [ev("t27", "2026-08-28T11:00:00.000Z", "Completed")],
  },
  {
    id: "ord-011",
    ticket: "PTG-20260820-031",
    createdAt: "2026-08-20T10:00:00.000Z",
    customerId: "cus-abc",
    files: [
      {
        id: "f-12",
        name: "Visitor Passes.pdf",
        type: "application/pdf",
        size: 300000,
        spec: {
          service: "ID / Cards",
          paperSize: "Custom",
          customSize: "ID",
          paperType: "Cardstock",
          color: "Colored",
          sides: "Single-sided",
          quantity: 50,
          finishing: ["Lamination", "Cutting"],
        },
      },
    ],
    fulfillment: "pickup",
    status: "completed",
    paymentStatus: "monthly",
    priority: "normal",
    quotation: {
      lines: [{ id: "q21", description: "50 laminated visitor passes", amount: 800 }],
      discount: 0,
    },
    amountPaid: 0,
    timeline: [ev("t28", "2026-08-20T10:00:00.000Z", "Completed")],
  },
  {
    id: "ord-012",
    ticket: "PTG-20260903-012",
    createdAt: "2026-09-03T13:15:00.000Z",
    customerId: "cus-maria",
    files: [
      {
        id: "f-13",
        name: "Birthday Tarpaulin.jpg",
        type: "image/jpeg",
        size: 4100000,
        spec: {
          service: "Posters",
          paperSize: "Custom",
          customSize: "2 × 4 ft tarp",
          paperType: "Other",
          color: "Colored",
          sides: "Single-sided",
          quantity: 1,
          finishing: ["Packaging"],
        },
      },
    ],
    fulfillment: "delivery",
    delivery: {
      contactName: "Maria Santos",
      mobile: "09228881122",
      pin: {
        lat: 14.2801,
        lng: 121.1244,
        address: "Brgy. Banay-Banay, Cabuyao, Laguna",
      },
    },
    status: "finishing",
    paymentStatus: "paid",
    priority: "high",
    quotation: {
      lines: [
        { id: "q22", description: "2×4 ft tarpaulin", amount: 450 },
        { id: "q23", description: "Delivery · Zone 1", amount: 50 },
      ],
      discount: 0,
    },
    amountPaid: 500,
    timeline: [
      ev("t29", "2026-09-03T13:15:00.000Z", "Request submitted"),
      ev("t30", "2026-09-03T14:00:00.000Z", "In finishing"),
    ],
  },
];

export function createSeed(): AppState {
  return {
    session: { role: "guest" },
    customers,
    orders,
    runs: [
      {
        id: "run-001",
        name: "Delivery Run #001",
        driver: "John Ramos",
        createdAt: "2026-09-02T15:40:00.000Z",
        orderIds: ["ord-004"],
        status: "done",
      },
    ],
    catalog: [
      { id: "c1", category: "Document Printing", name: "A4 B&W", description: "Standard office copies", unit: "page", basePrice: 5 },
      { id: "c2", category: "Document Printing", name: "A4 Color", description: "Full-color documents", unit: "page", basePrice: 15 },
      { id: "c3", category: "Document Printing", name: "A3 Color", description: "Large format color", unit: "page", basePrice: 25 },
      { id: "c4", category: "Document Printing", name: "Legal", description: "Legal-size copies", unit: "page", basePrice: 6 },
      { id: "c5", category: "Document Printing", name: "Letter", description: "US Letter copies", unit: "page", basePrice: 5 },
      { id: "c6", category: "Photo Printing", name: "2R", description: "Wallet photos", unit: "print", basePrice: 8 },
      { id: "c7", category: "Photo Printing", name: "3R", description: "Standard photo", unit: "print", basePrice: 10 },
      { id: "c8", category: "Photo Printing", name: "4R", description: "Classic photo print", unit: "print", basePrice: 15 },
      { id: "c9", category: "Photo Printing", name: "5R", description: "Large photo", unit: "print", basePrice: 25 },
      { id: "c10", category: "Photo Printing", name: "8R", description: "Portrait photo", unit: "print", basePrice: 45 },
      { id: "c11", category: "Business Printing", name: "Business Cards", description: "Full-color calling cards", unit: "100 pcs", basePrice: 450 },
      { id: "c12", category: "Business Printing", name: "Flyers", description: "A4 promo flyers", unit: "100 pcs", basePrice: 800 },
      { id: "c13", category: "Business Printing", name: "Brochures", description: "Tri-fold brochures", unit: "100 pcs", basePrice: 1200 },
      { id: "c14", category: "Business Printing", name: "Posters", description: "A3 posters", unit: "piece", basePrice: 45 },
      { id: "c15", category: "Business Printing", name: "Tarpaulin", description: "Outdoor tarp per sq ft", unit: "sq ft", basePrice: 18 },
      { id: "c16", category: "Finishing", name: "Lamination", description: "Hot lamination", unit: "sheet", basePrice: 15 },
      { id: "c17", category: "Finishing", name: "Binding", description: "Soft bind", unit: "set", basePrice: 80 },
      { id: "c18", category: "Finishing", name: "Cutting", description: "Trim to size", unit: "job", basePrice: 30 },
      { id: "c19", category: "Finishing", name: "Folding", description: "Machine fold", unit: "100 pcs", basePrice: 40 },
    ],
    priceRules: [
      { id: "p1", name: "A4 B&W", kind: "print", unitPrice: 5, minQty: 1, maxQty: 99 },
      { id: "p2", name: "A4 B&W bulk 100+", kind: "print", unitPrice: 4, minQty: 100, maxQty: 499 },
      { id: "p3", name: "A4 B&W bulk 500+", kind: "print", unitPrice: 3.5, minQty: 500 },
      { id: "p4", name: "A4 Color", kind: "print", unitPrice: 15, minQty: 1, maxQty: 99 },
      { id: "p5", name: "A4 Color bulk", kind: "print", unitPrice: 12, minQty: 100 },
      { id: "p6", name: "Lamination", kind: "finishing", unitPrice: 15 },
      { id: "p7", name: "Binding", kind: "finishing", unitPrice: 80 },
      { id: "p8", name: "Spiral Binding", kind: "finishing", unitPrice: 90 },
      { id: "p9", name: "Stapling", kind: "finishing", unitPrice: 5 },
      { id: "p10", name: "Cutting", kind: "finishing", unitPrice: 30 },
      { id: "p11", name: "Folding", kind: "finishing", unitPrice: 20 },
      { id: "p12", name: "Packaging", kind: "finishing", unitPrice: 20 },
      { id: "p13", name: "Mounting", kind: "finishing", unitPrice: 60 },
      { id: "p14", name: "Rush", kind: "rush", unitPrice: 150 },
    ],
    zones: [
      { id: "z1", name: "Zone 1", fee: 50, cities: ["Cabuyao"] },
      { id: "z2", name: "Zone 2", fee: 80, cities: ["Santa Rosa", "Biñan"] },
      { id: "z3", name: "Zone 3", fee: 120, cities: ["Calamba"] },
      { id: "z4", name: "Zone 4", fee: 150, cities: ["San Pedro", "Carmona"] },
    ],
    promos: [
      { id: "pr1", code: "PRINT10", description: "10% off first or repeat orders", kind: "percent", value: 10, active: true },
      { id: "pr2", code: "FREEDEL", description: "Free delivery in Zone 1–2", kind: "free_delivery", value: 0, active: true },
      { id: "pr3", code: "WELCOME50", description: "₱50 off first order", kind: "fixed", value: 50, active: true },
    ],
    printers: [
      { id: "prt-1", name: "Front counter color", model: "Canon PIXMA G3010", paper: "A4", color: true, location: "Front desk" },
      { id: "prt-2", name: "Production B&W", model: "HP LaserJet Pro", paper: "A4", color: false, location: "Print room" },
      { id: "prt-3", name: "A3 poster", model: "Epson L1800", paper: "A3", color: true, location: "Large-format table" },
      { id: "prt-4", name: "Photo printer", model: "Canon SELPHY / photo tray", paper: "A4", color: true, location: "Photo station" },
    ],
    selectedPrinterId: "prt-1",
  };
}
